# Generated by Django 6.0.7 on 2026-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('VERIFY_EMAIL', 'Verify Email'), ('RESET_PASSWORD', 'Reset Password')], default='VERIFY_EMAIL', max_length=20),
            preserve_default=False,
        ),
    ]
