# Generated by Django 6.0.7 on 2026-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accepted'), ('friend_rejected', 'Friend Rejected'), ('post_like', 'Post Like'), ('comment', 'Comment')], max_length=30),
        ),
    ]
