# Generated by Django 6.0.7 on 2026-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('friend_rejected', 'Friend Rejected'), ('post_like', 'Post Like'), ('comment', 'Comment')], max_length=30),
        ),
    ]
