# Generated by Django 6.0.7 on 2026-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('friend_rejected', 'Friend Rejected'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('post_share', 'Post Share')], max_length=30),
        ),
    ]
